# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageDemo
	pod 'swift-vibrant'
  target 'ImageDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageDemoUITests' do
    # Pods for testing
  end

end
